### ISSUE TITLE
Add size required by VDC for Kubernetes VM

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/vdc#39]
> additional Kubernetes node
> 
> small: 1vcpu, 2 GB mem, 25 GB max storage: 5 EUR
> mid: 2vcpu, 4 GB mem, 50 GB max storage: 10 EUR
> big: 4vcpu, 8 GB mem, 50 GB max storage: 20 EUR

these sizes are not supported by zos.
current sizes: https://github.com/threefoldfoundation/info_gridmanual/blob/410ca5f0c74ad119f04a86b579ff8dc4edeac5f3/src/smartcontract_for_it/capacity_kubernetes.md#vm-sizes

_Originally posted by @m-motawea in https://github.com/threefoldtech/home/issues/949#issuecomment-730205221_

**Comment by despiegk** [comment]
do note that we don't charge TFT for the storage as part of the CU, 
see the definition on wiki: https://wiki.threefold.io/#/cloud_units
make sure this is part of the 2.3 even (if needed still change in field, this is blocker because our pricing is crazy now for storage)

so that table needs to be converted to CU
and we charge for CU

3 different types per CU
and then 0.5 CU, 1 CU, 2 CU, ...

let me review please

**Comment by zaibon** [comment]
This is very unfortunate. We just created a all bunch a new size for K8S. I did asked confirmation by everyone for the new sizes and nothing has been mentioned regarding the one required for the VDC: https://github.com/threefoldtech/home/issues/923

> so that table needs to be converted to CU
and we charge for CU

All the capacity is always charged by CU/SU (cloud units).

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zos/pull/1077
https://github.com/threefoldtech/js-sdk/pull/1729
https://github.com/threefoldtech/tfexplorer/pull/220
